---
language: bash


sudo: false

install:
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g elm@0.17.0 elm-test@0.16.1-alpha4
  - elm package install -y

script:
  - bin/fetch-configlet
  - bin/configlet .
  - bin/build.sh

cache:
  directories:
  - elm-stuff
